name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract ZIP
        run: unzip root.zip

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Release APK
        run: |
          # यह कमांड अपने आप आपके zip वाले फोल्डर के अंदर चली जाएगी
          FOLDER=$(ls -d */ | grep -v "^\." | head -n 1)
          cd "$FOLDER"
          flutter clean
          flutter pub get
          # --verbose डालने से हमें एरर की पूरी जानकारी मिलेगी
          flutter build apk --release --verbose

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: my-release-apk
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
